Fixed GLES20 NoSuchMethodError on Android API < 17
The new GLES20 code used some convenience methods that were added in API 17, causing instant crashes on older devices. This PR swaps out these methods for older ones that should be compatible with all API levels supported by libGDX.